id: A10C991C1
title: The Single-Page Practice of the Guru of Great Bliss
type: translation
pechas:
- I007B8F22
- I89B5B890
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:59.713730
  last_modified_at: 2023-01-04 11:33:59.713741
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I007B8F22/A9B4: 005E
  I89B5B890/6692: 005E
